const darkChartColors = [
  "DarkSlateGray",
  "DarkOliveGreen",
  "SlateGray",
  "DarkSlateBlue",
  "DarkCyan",
  "DarkGoldenrod",
  "DarkMagenta",
  "DarkOrchid",
  "DarkRed",
  "DarkSalmon",
  "DarkSeaGreen",
  "DarkTurquoise",
  "DarkViolet",
  "DimGray",
  "MidnightBlue",
  "RebeccaPurple",
  "Teal",
  "OliveDrab",
  "Sienna",
  "Indigo",
  "FireBrick",
  "Maroon",
  "MediumBlue",
  "Purple",
  "SaddleBrown",
  "SteelBlue",
  "CadetBlue",
  "Olive",
  "MediumPurple",
  "DarkKhaki",
];

export default darkChartColors